sonar.projectKey=sistema-itinerarios-personales
sonar.projectName=Sistema Distribuido de Itinerarios Personales
sonar.projectVersion=1.0.0
sonar.sources=services
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/alembic/**,**/tests/**,**/venv/**,**/__pycache__/**
sonar.qualitygate.wait=true
