services:
  airport-service:
    build:
      context: ../..
      dockerfile: services/airport-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - REDIS_URL=redis://redis-airport:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - redis-airport
    networks:
      - airport-net

  redis-airport:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - airport-net

networks:
  airport-net:
    driver: bridge
